### PR TITLE
remove teanjs (project is not maintained since 2019)

### PR DESCRIPTION
**Pull request by dlukanin**

### CODE REVIEW

**Comment by juliandavidmr** [comment]
Hi @adrien2p, the project is managed by you, it has not been supported since 2019, I would like to know if there are future proposals that will allow you to keep it updated.

**Comment by evereq** [comment]
@dlukanin I would like to propose a separate section for "Unmaintained" projects. Because some people might still be interested to find such projects... Not sure what is best practice in such cases for "awesome" lists?

**Comment by adrien2p** [comment]
Hello there !

Unfortunately there is not much people that seems interested. If anyone propose something they would like to see I could update it. 

But as suggested earlier I think an unmainted section could be awesome since people could be interested in it.

**Comment by juliandavidmr** [comment]
I agree with @evereq and @adrien2p.

In the next few days, I will create the section "Unmaintained", if someone wants to create this section soon, then I will be waiting to receive a PR.

**Comment by juliandavidmr** [comment]
Thanks, @dlukanin for your collaboration, however, this PR is no longer valid according to what we have commented previously, so I will close this PR.

**Comment by juliandavidmr** [comment]
Thanks, @dlukanin for your collaboration, however, this PR is no longer valid according to what we have commented previously, so I will close this PR.

**Pull request closed without merging**
