### PR TITLE
Add Nest JSON RPC Transport

### PR DESCRIPTION
**Pull request by p0vidl0**

### CODE REVIEW

**Comment by juliandavidmr** [comment]
Can you update the Readme file?

You can have this file as a reference:
https://github.com/RickCogley/Github-Markdown-Reference/blob/master/README.md

**Comment by juliandavidmr** [comment]
Too, add LICENSE.md file.

**Comment by p0vidl0** [comment]
Unfortunately, isn't my repo, I'm just using it)

**Comment by Insidexa** [comment]
@p0vidl0 Thank yoy for create PR with my lib NestJS JSON RPC

@juliandavidmr I add `MIT` license to repository

**Comment by juliandavidmr** [comment]
Hi @p0vidl0 @Insidexa 
Thanks so much for your contributions.

**Pull request merged**
