### PR TITLE
Added Mailman and Eyewitness

### PR DESCRIPTION
**Pull request by vinayak25**
Added Mailman and Eyewitness.

Mailman - https://github.com/squareboat/nest-mailman
Eyewitness - https://github.com/squareboat/nest-eyewitness

### CODE REVIEW

**Comment by juliandavidmr** [comment]
Hi, this PR has a [problem](https://travis-ci.org/github/juliandavidmr/awesome-nestjs/builds/738995334):

✖  132:61  List item description must start with valid casing  awesome/list-item

**Comment by juliandavidmr** [comment]
[nest-eyewitness](https://github.com/squareboat/nest-eyewitness) has less than 10 stars.

If you want, you can send a PR that contains only the first link (Mailman)

**Comment by vinayak25** [comment]
Hi @juliandavidmr, the eyewitness seems to have 10 stars. Please check

**Comment by juliandavidmr** [comment]
A star has arrived at the last minute 😂

Before to continue... Check [this](https://travis-ci.org/github/juliandavidmr/awesome-nestjs/builds/738995334#L247):

✖ 132:61 List item description must start with valid casing awesome/list-item

**Comment by vinayak25** [comment]
@juliandavidmr the PR is updated now. Please check

**Comment by juliandavidmr** [comment]
Thanks for your contribution.

**Pull request merged**
