### PR TITLE
add nestjs extended multer module

### PR DESCRIPTION
**Pull request by jeffminsungkim**

### CODE REVIEW

**Comment by juliandavidmr** [comment]
Hi @jeffminsungkim 

Thanks for your contribution. But I need that added item be moved to the "Utils" category. Also undo the changes made to the table of contents.

**Comment by jeffminsungkim** [comment]
@juliandavidmr Hey, Julian. I've fixed it. `Markdown All in One` extension caused some trouble with the contents.

**Comment by jeffminsungkim** [comment]
@juliandavidmr Is there anything I can do for you?

**Comment by juliandavidmr** [comment]
@jeffminsungkim thank you for your contribution, I hope your tool is very successful.

**Comment by jeffminsungkim** [comment]
@juliandavidmr Can I use the badge now?!

**Comment by juliandavidmr** [comment]
@jeffminsungkim Which badge?

**Comment by jeffminsungkim** [comment]
@juliandavidmr Awesome mentioned badge I guess?

**Comment by juliandavidmr** [comment]
@jeffminsungkim 

Awesome-nest is not within the Awesome-list of Sindresorhus.  In other words, the Awesome badge was placed inside this repository, however it was never added to the Sindresorhus repo.

I guess you can place the badge, this while Awesome-nest is officially accepted as Awesome.

**Comment by jeffminsungkim** [comment]
@juliandavidmr 

I inquired about the badge because, you're the maintainer of this repo and the `Awesome-nest` is officially accepted as Awesome. 

According to the awesome manifesto, 
> This badge is for projects being mentioned in an Awesome list (NOT for use in Awesome lists). For example, the Chalk project could feature this badge because it's listed in Awesome Node.js. It's totally optional for projects, but it's a nice way to show they've been featured in an Awesome list. You can choose either the regular badge or the flat one.

Thank you Julian.

**Comment by juliandavidmr** [comment]
@jeffminsungkim 

Sorry, I didn't know the Awesome manifesto, I thank you for clarifying it.

**Comment by jeffminsungkim** [comment]
@juliandavidmr 

So I can use the badge right? Lol

**Comment by juliandavidmr** [comment]
@jeffminsungkim 

According to what you found in the manifesto, yes.

**Pull request merged**
