### PR TITLE
Add the Knests Stack

### PR DESCRIPTION
**Pull request by tudorconstantin**

### CODE REVIEW

**Comment by juliandavidmr** [comment]
Hi @tudorconstantin 

Do you have a demo? I would like to see it without having to mount the project.

Secondly, I think that the description is very long. You could have a description like this:
_"Full stack/end starter with: PostgreSQL, Knex.js, NestJS, Next.js, GraphQL, React, Material-UI, Docker multistage images for, Docker compose and a Gitlab CI/CD pipeline fully configured."_

_(The above description is just a suggestion)_.

Thanks.

**Comment by tudorconstantin** [comment]
Hi @juliandavidmr 

Indeed, the aspect is very important and is one thing which I also look at in a new project if it has one. I don't have a hosted version yet, so I added a few screenshots to the README, together with a link to the full theme I chose to integrate with the boilerplate.

Thanks for the observation regarding the description. I agree that more concise is better and your rephrasing is indeed much better.

Unfortunately I started cleaning some of the github repos I forked, and it's not possible for me to edit this PR.

Should I close this and open a new one? Or is it simpler if you to edit the description with your text after accepting the PR?

**Comment by juliandavidmr** [comment]
Unfortunately I can't edit the file because the source doesn't exist.

However, I will accept your PR and then edit the description. This way your name will not be lost in the list of contributors

**Comment by tudorconstantin** [comment]
thank you too!

**Pull request merged**
