### PR TITLE
Add Nonfig for Cloud managed configuration management system

### PR DESCRIPTION
**Pull request by Sharique-Hasan**
Nonfig combines Configurations and Features. So you change features, and release swiftly, and measure to digital impact.

### CODE REVIEW

**Comment by juliandavidmr** [comment]
Duplicate link, can you delete an item?

**Comment by Sharique-Hasan** [comment]
What to do if the project is lying under 2 categories?

**Comment by juliandavidmr** [comment]
Ideally, it should belong to just one. What category is ideal for the repository?

It could be kept within Utils.

**Comment by Sharique-Hasan** [comment]
Well the ideal category is the Managed Configurations

**Comment by juliandavidmr** [comment]
Thanks for u contribution.

**Pull request merged**
