### PR TITLE
Add new error handler module 'nestjs-enlighten'

### PR DESCRIPTION
**Pull request by ozkanonur**

### CODE REVIEW

**Comment by ozkanonur** [comment]
Still waiting for it, please update me if there is anything wrong.

**Comment by juliandavidmr** [comment]
Hi @ozkanonur, sorry for not checking your PR sooner. Can you fix the header images?

image

Is there a demo where I can see an implementation of your library?

**Comment by ozkanonur** [comment]
> 
> 
> Hi @ozkanonur, sorry for not checking your PR sooner. Can you fix the header images?
> 
> image
> 
> Is there a demo where I can see an implementation of your library?

The images are working actually. Sometimes it gets that problem but thats from shield.io not me. Just refresh the page then it will be fine when you see that corrupted images.

Its very simple to use, I show it clearly in documentation, should I make a demo repo anyway ?

**Comment by juliandavidmr** [comment]
I reloaded the site several times but the images never load. Regarding the demo, I wanted to see your library working without having to mount a project :sweat_smile: :wink:.

Thanks for your contribution.

**Pull request merged**
