### PR TITLE
docs: golevelup nestjs modules

### PR DESCRIPTION
**Pull request by WonderPanda**

### CODE REVIEW

**Comment by WonderPanda** [comment]
Hey @juliandavidmr thanks for putting together this awesome community resource! Is there anything blocking this one from making it through?

**Comment by juliandavidmr** [comment]
Hi @WonderPanda,

1. I understand that you have many packages in a single repository, is there a way to see installation statistics for each package?

2. Moreover, there are packages that require documentation standard, e.g. usage examples, how to install, referencing the current license, etc. i.e:

https://github.com/golevelup/nestjs/tree/master/packages/graphql-request
https://github.com/golevelup/nestjs/tree/master/packages/common

**Comment by WonderPanda** [comment]
Hey thanks for the reply.

1. The linked readme for each individual package includes links to NPM and usage statistics.

2. Makes sense for `graphql-request` as I'm proposing that one be added to the Awesome List so I can definitely add additional info, but common is lower level and wasn't being included in this PR. The top level repository license applies to all packages in the repo. Do you want me to call that out more specifically somehow? If so where do you want me to put it and what language makes most sense?

I'm happy to make the necessary changes

**Comment by juliandavidmr** [comment]
Updating `graphql-request` is sufficient.

**Comment by WonderPanda** [comment]
Hey @juliandavidmr I've update the graphql-request package readme and published new versions so that they're up to date on both GitHub and NPM. I appreciate you maintaining quality control here as the docs for that one definitely did need some love. Let me know if there's anything else you'd like to see for this to go through

**Comment by juliandavidmr** [comment]
Hi @WonderPanda 

All right,

A detail was missing which I have put in the following PR:

https://github.com/golevelup/nestjs/compare/master...juliandavidmr:patch-1

**Comment by WonderPanda** [comment]
> Hi @WonderPanda
> 
> All right,
> 
> A detail was missing which I have put in the following PR:
> 
> [golevelup/nestjs@master...juliandavidmr:patch-1](https://github.com/golevelup/nestjs/compare/master...juliandavidmr:patch-1)

This is a great addition. I'm going to quickly add it to the all of the different package readmes

**Pull request merged**
