### PR TITLE
Nestjs Session

### PR DESCRIPTION
**Pull request by iamolegga**

### CODE REVIEW

**Comment by iamolegga** [comment]
Hey, @juliandavidmr , can we merge it? ) It has 10 stars

**Comment by iamolegga** [comment]
@juliandavidmr 🙄

**Comment by iamolegga** [comment]
Here is the link to check stargazers in one second with one click: https://github.com/iamolegga/nestjs-session/stargazers
So it should take one second to check and one second to press the button `merge`

Thank you @juliandavidmr

**Comment by juliandavidmr** [comment]
Keep calm @iamolegga, I will merge your changes. Thanks for your patience. ;)

**Pull request merged**
